### ISSUE TITLE
Temporarily ignore noisy applications

### ISSUE THREAD

**Issue by muymoo** [cloudfoundry-community/splunk-firehose-nozzle#114]
Goal: Temporarily stop log collection from noisy CF apps => not go over Splunk license limit.

I'm thinking a simple env variable like `ExtraFields` where we can list:

`export IGNORED_APPS=app_guid_01,app_guid_02,app_guid_03`

and then restart nozzle to pick up environment variable. 

Bonus points: Don't require restart of nozzle so we don't have to refill boltdb app cache.

Happy to make PR if you agree this should be added.

**Comment by chenziliang** [comment]
Thanks Matt! 

we already have an opt-in solution which is setup env variable for F2S_DISABLE_LOGGING to "true" when deploying  PCF app. The log will be discarded automatically for app with this env setup.

BTW, we didn't document this env variable since we didn't hear any use cases until now.

Will this solve your problem ?

**Comment by muymoo** [comment]
That needs to be done by the application owner and have their app restarted. We don't have control over that and need to be able to disable without modifying their application. Do you know of a way to add this without restarting app etc?

**Comment by chenziliang** [comment]
I guess there is no way to inject one env to existing running app without redeployment/restart.
Ignoring logs from apps is essentially one of the use case of index routing. In index routing, when user configure null index for app IDs, logs get discarded.

We will probably revisit index routing in next release since our current release plan is sealed. 
BTW, we have a separated branch `feature/issue8-index-routing` which already implements the index routing feature, if you would like to try i am happy to merge back all new changes from develop to make the index routing branch with all fixes and enhancement after it was created.

**Comment by muymoo** [comment]
I think the nil case may be guarded against?
```
	// If index is "", we can't set empty index due to HEC will
	// disard events with index=""
	if index != nil && *index != "" || index == nil {
		event["index"] = index
	}
```
We don't need full index routing, although that is a nice to have. A simple list of guids to ignore would be enough for now. Whichever you think is best. Happy to test it out.

**Comment by chenziliang** [comment]
@muymoo nil case is a valid one which drop all of events. There are 2 valid cases when setting "index"
1. non-nil non-empty index
2. nil index

The other valid case is not setting "index" at all which goes to HEC default index

**Comment by muymoo** [comment]
That seems a bit tricky to understand when configuring. Is this correct?
 1. non-nil non-empty index (app_1234:"main_index") -> sends events to main_index
 2. nil index (app_1234:"") -> Ignores events for app_1234
Question: Isn't this "empty" not nil? I don't believe a string can be nil
Feedback: This seems like a "hack" to ignore apps. It seems like a side effect of the configuration. 
 3. unset index () -> sends app_1234 events to default HEC index

For my specific use case, a simple list of guids to ignore would be ideal.

**Comment by chenziliang** [comment]
Index for (app_1234: "") is not nil, instead it is empty and we will use HEC default index when user sets up an empty index.

Empty index is not valid in HEC, we have 2 choices here ignore all events or let events go to HEC default index. We chose the later.

(app_123: null) is nil index, and we ignore all events.

**Comment by luckyj5** [comment]
Please re-open is needed. 
Closing this old issue.

**Comment by hanswurscht** [comment]
So what is the proper solution to temporary ignore chatty applications?
Is it possible to just ignore logs from stdout/stderr but keep the container metrics?
