### ISSUE TITLE
Missing fields after some time in cf:logmessage

### ISSUE THREAD

**Issue by hanswurscht** [cloudfoundry-community/splunk-firehose-nozzle#121]
Hi,

we experience missing fields in sourcetype cf:logmessage sent by splunk-firehose-nozzle to our splunk indexcluster.
After some time specific fields, for example cf_app_name, are missing in splunk. Other fields like cf_app_id are filled correctly.

A restart of the nozzle helps to solve that problem so that the field cf_app_name is set and filled correctly again.

We were not able to narrow down the problem in more detail.
We are using the latest development version.

Do you need more information to track the problem?

Thanks
- Lorenz

**Comment by chenziliang** [comment]
If the missing app name is a new app, it is expected since internally nozzle refreshes the app metadata information periodically from cloud controller. So the app metadata in memory may be stale sometimes. The refresh cycle is configurable. Please refer to the README for more details. Rebooting the nozzle always cause a cache refresh.

**Comment by dtregonning** [comment]
Closing after refresh app advise provided.
@hanswurscht -> Please reopen with comments if this is still an issue.
