### ISSUE TITLE
Eliminate BoltDB and switch to memory cache

### ISSUE THREAD

**Issue by chenziliang** [cloudfoundry-community/splunk-firehose-nozzle#47]
For now, we laverage BoltDB to cache application data locally for each nozzle. Since nozzle is usually deployed in a container env in CloudFoundry env, when nozzle restarts, the container will be gone and also for local boltDB ckpt file which makes the boltdb's benefits less useful since every time we will need build the cache anyway when nozzle restarts.

Switching to a in memory cache which has the same interface seems reasonable to go

**Comment by psychickita** [comment]
In-memory cache will need to be rebuilt on nozzle redeploy as well, so what is the benefit of proposed redesign?

**Comment by chenziliang** [comment]
It is simpler to me. According to CF suggestion, it is not recommended to write to local file system since it doesn't help much. https://docs.cloudfoundry.org/devguide/deploy-apps/prepare-to-deploy.html

**Comment by chenziliang** [comment]
With removing the local boltdb, we can also more easily run multiple nozzle in one VM if necessary.

**Comment by chenziliang** [comment]
@cholick, could you please share more thoughts about this since I may not have full understanding/context about the local boltdb cache ?

**Comment by cholick** [comment]
boltdb is less relevant the app container, true, but this code was designed for: https://github.com/cloudfoundry-community/splunk-firehose-nozzle-release - where it's running on a vm and the cache doesn't disappear. Running on cloud foundry itself is just on way to deploy the code, and not the method we're deploying with when distributing on PivNet to customers.

Also, the doc you mention @chenziliang states the file system isn't suitable for many things because is short lived and not shared. Those are, however, not problematic constraints for this use case: a cache.

I was also talking to a different user of the nozzle who has 42k apps. The current implementation is not able to populate the cache fast enough via the cloud foundry API. He worked around the problem by pre-priming the disk cache and thus starting the nozzle with metadata from most apps: this customer needed the disk cache as a workaround.

**Comment by psychickita** [comment]
Matt,

Can you tell us more about customer’s workaround? Any other suggestions to handle app info between restarts or redeployments?

Thanks,
Marian

**Comment by chenziliang** [comment]
Thanks @cholick. So in production, user are deploying nozzle just in a VM instead of a CF container ? May i ask how does end user to scale out the nozzle ? Scale out multiple VMs ?

**Comment by cholick** [comment]
@chenziliang Yeah, but it's a BOSH release. So scaling out is a matter of changing a single number. Trivial. Customers can deploy just the nozzle itself, that's just not what the BOSH release does. The full shape of that might be a bit easier to explain fully in person, @rarsan and @luckyj5 both have more details.

@psychickita the `caching.Caching` interface has `GetAllApp`, so you can build up a warm cache of the current installation. Then just push that database with the app. It exposes a real problem for installations that have a massive number of apps, but he used that as a clever workaround.

**Comment by chenziliang** [comment]
@cholick thanks. Just for curiosity, is 42k applications normal. It seems a super huge production env, and wondering if there are too many dummy/testing apps for this customer.

**Comment by cholick** [comment]
No: that's really, really large.

**Comment by chenziliang** [comment]
Setup some in-memory cache in front of boltdb improve lots of perf. https://github.com/cloudfoundry-community/firehose-to-syslog/pull/153. We merge the changes to splunk nozzle
